INSERT INTO amenity (amenity) VALUES ('Dog Friendly');
INSERT INTO amenity (amenity) VALUES ('Cat Friendly');
INSERT INTO amenity (amenity) VALUES ('turtle friendly');
INSERT INTO amenity (amenity) VALUES ('chicken friendly');
INSERT INTO amenity (amenity) VALUES ('restrooms');
INSERT INTO amenity (amenity) VALUES ('fence area');
INSERT INTO amenity (amenity) VALUES ('hot dog stand');
INSERT INTO amenity (amenity) VALUES ('parking area');
INSERT INTO amenity (amenity) VALUES ('wifi');
INSERT INTO amenity (amenity) VALUES ('vending machines');
INSERT INTO amenity (amenity) VALUES ('lake');
INSERT INTO amenity (amenity) VALUES ('docent');
